# Project: Project3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = C.S.P0006.o
LINKOBJ  = C.S.P0006.o
LIBS     = -L"D:/Code name/BShed/Dev-Cpp/MinGW64/lib" -L"D:/Code name/BShed/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/Code name/BShed/Dev-Cpp/MinGW64/include" -I"D:/Code name/BShed/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Code name/BShed/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Code name/BShed/Dev-Cpp/MinGW64/include" -I"D:/Code name/BShed/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Code name/BShed/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Code name/BShed/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = C.S.P0006.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

C.S.P0006.o: C.S.P0006.c
	$(CC) -c C.S.P0006.c -o C.S.P0006.o $(CFLAGS)
